-- Your SQL goes here
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users ( 
  id SERIAL PRIMARY KEY,
  user_uid VARCHAR(128) NOT NULL DEFAULT uuid_generate_v4(), 
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
  name VARCHAR(128) NOT NULL
)
